name: Generate ASCII Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Excecute conwsay command
        run: cowsay -f parrot "This is parrot ASCII diagram" > parrot.txt
      
      - name: Test File Exists
        run: grep -i parrot "parrot.txt"
        
      - name: Read file
        run: cat parrot.txt

      - name: Checkout Repo files
        run: ls -al