name: Running Multiple Jobs

on:
  push:

jobs:
  build_job1:
    runs-on: ubuntu-latest

   steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Docker Login
        run: echo docker login --password=${{ secrets.Docker_Password }}

      - name: Install Cowsay Program
        run: sudo apt-get update && sudo apt-get install cowsay -y

      - name: Create Dragon Text File
        run: |
          /usr/games/cowsay -f dragon "This is content for dragon.txt" > dragon.txt

      - name: Display Dragon File
        run: cat dragon.txt

      - name: Upload Dragon Text File
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: dragon.txt

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest

    steps:
      - name: Download Dragon Text File
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: .

      - name: List Files
        run: ls -l

      - name: Test File Exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest

    steps:
      - name: Download Dragon Text File
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          path: .

      - name: Display Dragon File
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying Application..."