name: practice_workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -l

      - name: Give execute permission
        run: chmod +4 shellscript.sh

      - name: Executing shell script
        run: ./shellscript.sh