name: First Workflow File

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v6
        - name: List and Read File
          run: |
            echo "File Listing"
            ls -al
            cat README.md 
        - name: Generate ASCII Network
          run:  cowsay -f parrot "This is parrot ASCII diagram" >> parrot.txt
       # - name: list files
       #   run: ls 
       # - name: Read file
       #   run: cat README.md